### ISSUE TITLE
add support for installation via package manager

### ISSUE THREAD

**Issue by SergeyMi37** [alexatwoodhead/GoSelector#1]

**Comment by SergeyMi37** [comment]
Your class has not been set. You need to add a resource to the module and change the class format to UDL

**Comment by alexatwoodhead** [comment]
Have added resource element to Module and created a second folder "udl" for UDL source content.
Retained the XML format for another person.
See if it republishes well. Thanks for hints.

**Comment by SergeyMi37** [comment]
Class format on UDL implies CLS file format. See the [wiki](https://github.com/intersystems-community/zpm/wiki/03.-Module.xml)  and how other projects are made, for [example](https://github.com/intersystems-community/isc-dev).
You can easily convert classes to UDL format using the `isc-dev` project.

**Comment by SergeyMi37** [comment]
I made you a [pull request](https://github.com/alexatwoodhead/GoSelector/pull/2) that will fix the bug and add docker to your project.
